#!/bin/sh
IP=pi@10.141.29.99
FPI="/home/pi/AVC/simple/main.cpp"
DPI="/home/pi/AVC/simple"
FPC="C:\Users\10jac\OneDrive\Documents\UNI\ENGR 101\AVC\avc\main.cpp"
echo Transferring
scp main.cpp $IP:$FPI
echo Compiling
#ssh $IP sh -c 'cd /home/pi/AVC/simple && ls && make'
ssh $IP make -c $DPI
echo Finished